enum PALQueueID {
  QUEUE_PS = 0, // QueueDeliveryType QTYPE_CALLBACK (0x2) [callback -> 0x40f58fb5]
  QUEUE_Background = 1, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> Background]
  QUEUE_AdcTask = 2, // QueueDeliveryType QTYPE_CALLBACK_BIOS (0x3) [task -> Background, callback -> 0x4162ded5]
  QUEUE_DBGCMD2 = 3, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> DBGCMD2]
  QUEUE_LTE_L1 = 4, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_ATI = 5, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_ATIPS = 6, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> ATI (5)]
  QUEUE_NS_SYNC = 7, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SISO = 8, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_L2HRX = 9, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HRX_L1LC = 10, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTERRC_INT = 11, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTERRC_DSDS_SYNC = 12, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_LTE_MMC_GRR = 13, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_MMC_GRR = 14, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTERRC = 15, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTERRC_L1 = 16, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC (15)]
  QUEUE_LTERRC_MAC = 17, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC (15)]
  QUEUE_LTERRC_RLC = 18, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC (15)]
  QUEUE_LTERRC_PDCP = 19, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC (15)]
  QUEUE_LTERRC_MM = 20, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC (15)]
  QUEUE_DBGCMD = 21, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SISO (8)]
  QUEUE_DS_CC = 22, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> CC (23)]
  QUEUE_CC = 23, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SAEL3 = 24, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SAEL3_SYNC = 25, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SAEMM = 26, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SAEL3 (24)]
  QUEUE_SAEQM = 27, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SAEL3 (24)]
  QUEUE_DS_SAEL3 = 28, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SAEL3_SYNC = 29, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SAEMM = 30, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> DS_SAEL3 (28)]
  QUEUE_DS_SAEQM = 31, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> DS_SAEL3 (28)]
  QUEUE_MM = 32, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SM = 33, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_MM = 34, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> MM (32)]
  QUEUE_DS_SM = 35, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SM (33)]
  QUEUE_LTE_TLP = 36, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_VCG = 37, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_MONITOR = 38, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SISO (8)]
  QUEUE_SS = 39, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SS = 40, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SS (39)]
  QUEUE_DS_LLC = 41, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LLC (45)]
  QUEUE_DS_SIM = 42, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_RLC = 43, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> RLC (47)]
  QUEUE_URRC = 44, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LLC = 45, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SIM = 46, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RLC = 47, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_VSUP = 48, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_STK = 49, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_GLAPD = 50, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_GMAC = 51, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> GMAC (58)]
  QUEUE_DS_GMM = 52, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> DS_MM (34)]
  QUEUE_DS_GRR = 53, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> GRR (60)]
  QUEUE_DS_GLAPD = 54, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> GLAPD (50)]
  QUEUE_DSRC = 55, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DSL1RC = 56, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SRL1RC = 57, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_GMAC = 58, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_GMM = 59, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> MM (32)]
  QUEUE_GRR = 60, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LAPD = 61, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_PPP = 62, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SMB = 63, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_UMAC = 64, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> UL1UL2Gateway (197)]
  QUEUE_UPDCP = 65, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> UL1UL2Gateway (197)]
  QUEUE_UPHY = 66, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> UL1UL2Gateway (197)]
  QUEUE_URLC = 67, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> UL1UL2Gateway (197)]
  QUEUE_UBMC = 68, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> UL1UL2Gateway (197)]
  QUEUE_TPHY = 69, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> UL1UL2Gateway (197)]
  QUEUE_LLR = 70, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_UIP = 71, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_UIP_SYN = 72, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SISO (8)]
  QUEUE_GAPI_SYN = 73, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SISO (8)]
  QUEUE_LCD = 74, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_CDH = 75, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_H223_DL = 76, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_H223_UL = 77, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DBG = 78, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_NS_SHP = 79, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SISO (8)]
  QUEUE_GDA = 80, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LRX_PHY_RRC = 81, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LRX_MAC_RRC = 82, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_PHY_RRC = 83, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_MAC_RRC = 84, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_RLC_RRC = 85, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HRX_RLC_RRC = 86, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HRX_PDCP_RRC = 87, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HTX_PDCP_RRC = 88, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_RRM_RRC = 89, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_RRM_INT = 90, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_RRM_L2LTX = 91, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_RRM_L2LRX = 92, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_RRM_L1LC = 93, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_RRM_TIMER = 94, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_MMC = 95, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_RRM = 96, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_RRM_SYNC2 = 97, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_INT = 98, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_HAL = 99, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_L1LC_L1TUNNEL = 100, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_L2LTX = 101, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_L2LRX = 102, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1LC_L2HTX = 103, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_IMSCC_L2LRX = 104, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_MMC = 105, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_RRM = 106, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_RRM_SYNC2 = 107, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_INT = 108, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_HAL = 109, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_L2LTX = 110, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_L2LRX = 111, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_L2HTX = 112, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DS_L1LC_L2HRX = 113, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_L1LC_L1TUNNEL = 114, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_L1NC_L1TUNNEL = 115, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_ASTUNNEL = 116, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LRX_HAL = 117, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LRX_L2HTX = 118, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_L2HTX = 119, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_L2LRX = 120, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_RRM = 121, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_L2LTX = 122, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_L1LC = 123, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_HAL = 124, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_IMSCC = 125, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HRX_L2HRX = 126, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HRX_L2LRX = 127, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HRX_L2LTX = 128, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HRX_HAL = 129, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HTX_HAL = 130, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HTX_NAS = 131, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HTX_L2LTX = 132, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HTX_L2HRX = 133, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HTX_L2HTX = 134, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HTX_L1LC = 135, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2TCM_L2HRX = 136, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2TCM_L2HTX = 137, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2TCM_L2LRX = 138, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2TCM_L2LTX = 139, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2TCM_HAL = 140, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LRX_TEST = 141, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L1TX_TEST = 142, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2TX_TEST = 143, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2RX_TEST = 144, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_PdcpToSb = 145, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_MTM = 146, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_MTM = 147, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_MTM_PHY = 148, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_DM = 149, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SMS = 150, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SMS = 151, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SMS (150)]
  QUEUE_L1CReceive = 152, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LCSM = 153, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_LCSM = 154, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LCSM (153)]
  QUEUE_OEMLITE = 155, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_H324M_UL = 156, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_H324M_DL = 157, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_HSPA_CALIBRATION_MBX = 158, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> HSPA_CALIBRATION]
  QUEUE_ATI_SYN = 159, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_L1CSave = 160, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_L1C_GDA = 161, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SNDCP = 162, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SNDCP = 163, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> SNDCP (162)]
  QUEUE_RABM = 164, // QueueDeliveryType QTYPE_CALLBACK (0x2) [callback -> 0x413d6f0b]
  QUEUE_UI = 165, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_PDH = 166, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_PBM = 167, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_PBM = 168, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_PacketHandler = 169, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_MTI = 170, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_MTI_FSBE = 171, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DM = 172, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DM_TX = 173, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_BDA = 174, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_CIQD = 175, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_REG_SAP = 176, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_CC_SS_SAP = 177, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_AS_SAP = 178, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SMS_SAP = 179, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DBG_SAP = 180, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SIM_SAP = 181, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_REG_SAP = 182, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_CC_SS_SAP = 183, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_AS_SAP = 184, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SMS_SAP = 185, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_DBG_SAP = 186, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SIM_SAP = 187, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_MMC = 188, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_MMC = 189, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> MMC (188)]
  QUEUE_HEDGE = 190, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_MMC_IF = 191, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SR_IF = 192, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_MMC_IF = 193, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> MMC_IF (191)]
  QUEUE_LTE_MMC = 194, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_MMC_GL1 = 195, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SIM_ATI = 196, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_UL1UL2Gateway = 197, // QueueDeliveryType QTYPE_CALLBACK (0x2) [callback -> 0x4077dc65]
  QUEUE_USAT = 198, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_USAT = 199, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_USAT_SYNC = 200, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_USAT_SYNC = 201, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_CC_SS_SAP_SYNC = 202, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SMS_SAP_SYNC = 203, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SIM_SAP_SYNC = 204, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_REG_SAP_SYNC = 205, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_CC_SS_SAP_SYNC = 206, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SMS_SAP_SYNC = 207, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_SIM_SAP_SYNC = 208, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_DS_REG_SAP_SYNC = 209, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS1 = 210, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS2 = 211, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS3 = 212, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS4 = 213, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS5 = 214, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS6 = 215, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS7 = 216, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS8 = 217, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS9 = 218, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_RFS10 = 219, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_TCPIP = 220, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_SISO_ASYNC = 221, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_IMS_CC = 222, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SRM = 223, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_VCE = 224, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LPP_RRC = 225, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LPP_EMM = 226, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LPP_NS = 227, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LPP_TLP = 228, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LPP_INT = 229, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTERRC_LPP = 230, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC (15)]
  QUEUE_ULDL = 231, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULDATA = 232, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULCC = 233, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULHISR = 234, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULUPHY = 235, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULRLC_RRC_DATA = 236, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULPCH_IND = 237, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULTME = 238, // QueueDeliveryType QTYPE_WAKEUP (0x5) [task -> UL2UL]
  QUEUE_ULSDUGEN = 239, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULRABMTICK = 240, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULVCG = 241, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULVGP = 242, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_ULURRC = 243, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_RLCMAC = 244, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2UL]
  QUEUE_DLDATA = 245, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2DL]
  QUEUE_DLHISR = 246, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2DL]
  QUEUE_DLTME = 247, // QueueDeliveryType QTYPE_WAKEUP (0x5) [task -> UL2DL]
  QUEUE_CCHISR = 248, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2CC]
  QUEUE_CCMAC_CONTROL = 249, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2CC]
  QUEUE_CCRLC_CONTROL = 250, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UL2CC]
  QUEUE_CCTME = 251, // QueueDeliveryType QTYPE_WAKEUP (0x5) [task -> UL2CC]
  QUEUE_INTDATA = 252, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DAUL = 253, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DADL = 254, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DAPDCP_CONTROL = 255, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DANAS = 256, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DARABM_VGP_CONTROL = 257, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DARABM_URRC_CONTROL = 258, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DACC = 259, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DALMAC = 260, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UDATA]
  QUEUE_DATME = 261, // QueueDeliveryType QTYPE_WAKEUP (0x5) [task -> UDATA]
  QUEUE_BMCCONTROL = 262, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UBMCTask]
  QUEUE_BMCRRC_CONTROL = 263, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UBMCTask]
  QUEUE_BMCL2DATA_IND = 264, // QueueDeliveryType QTYPE_STANDARD (0x1) [task -> UBMCTask]
  QUEUE_BACKTR = 265, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTERRC_DS = 266, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTERRC_L1_DS = 267, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC_DS (266)]
  QUEUE_LTERRC_MAC_DS = 268, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC_DS (266)]
  QUEUE_LTERRC_RLC_DS = 269, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC_DS (266)]
  QUEUE_LTERRC_PDCP_DS = 270, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC_DS (266)]
  QUEUE_LTERRC_MM_DS = 271, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> LTERRC_DS (266)]
  QUEUE_LTERRC_DSDS_SYNC_DS = 272, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LRX_PROSE = 273, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2LTX_PROSE = 274, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HTX_PROSE = 275, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_L2HRX_PROSE = 276, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_PDNMGR = 277, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_PMPM = 278, // QueueDeliveryType QTYPE_ALIAS (0x4) [alias -> PDNMGR (277)]
  QUEUE_SECU_REQ = 279, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SECU_ACK = 280, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTERRM = 281, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_NRRRM = 282, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SSH_MSG = 283, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_SHUB_ENT_MSG = 284, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_CPCOP_CLI_MSG = 285, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_CPCOP_SRC_MSG = 286, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_NRPDCP = 287, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTEPDCP = 288, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_NSA_RRC = 289, // QueueDeliveryType QTYPE_STANDARD (0x1)
  QUEUE_LTE_NSA_RRC_DS = 290, // QueueDeliveryType QTYPE_STANDARD (0x1)
};
